trigger_num: 4
poisoned_per_batch: 2

## gap 2 size 1*4 base (0, 0)
0_poison_pattern: [[0, 0], [0, 1], [0, 2], [0, 3]]
1_poison_pattern: [[0, 6], [0, 7], [0, 8], [0, 9]]
2_poison_pattern: [[3, 0], [3, 1], [3, 2], [3, 3]]
3_poison_pattern: [[3, 6], [3, 7], [3, 8], [3, 9]]